version: "3.4"
services:
    watcher:
        container_name: WATCHER
        image: node:20-alpine
        working_dir: /app
        command:
            - /bin/sh
            - -c
            - npm install && node_modules/.bin/tsc-watch --onCompilationStarted "rm done" --onSuccess "touch done"
        volumes:
            - ./:/app
